function [peak_sum_tbl, s0_s1_dist_tbl] ...
    ...
    = import_interstage_distance(...
    ...
s0_s1_path, peak_sum_tbl)

% load in Tom Wozny's (TW) error calculations of electrode location between
% stages 0 vs stage 1 (i.e., temporary vs permanent, NK vs RC+S, inpatient vs
% ambulatory) implants

tmp            = load(s0_s1_path);
s0_s1_dist_tbl = tmp.data;              clear tmp;


% remove stage 0 electrodes NOT permanently implanted
s0_s1_dist_tbl(...
                cellfun(@isempty, s0_s1_dist_tbl.SlicerClosestLabel),...
                :) = [];

s0_s1_dist_tbl.Subject = upper(s0_s1_dist_tbl.Subject);
%% reformat RBL labels of RC+S/NK electrodes to fit w/ TW labels
hemi_lbl_mat = split(...
                    replace(...   
                        replace(...
                                peak_sum_tbl.labels_1, {' ', '-'}, '_'), ...
                        {'RACCa', 'CM'}, {'RACC', 'CMPF'}),...
                    '_');

first_cont = cellfun(@(x, y) sprintf('%s%s', x, y), ...
            hemi_lbl_mat(:,2), hemi_lbl_mat(:,3), ...
            'UniformOutput', false);

second_cont = cellfun(@(x, y) sprintf('%s%s', x, y), ...
            hemi_lbl_mat(:,2), hemi_lbl_mat(:,4), ...
            'UniformOutput', false);

peak_sum_tbl.labels_1_1_TW_format = first_cont;
peak_sum_tbl.labels_1_2_TW_format  = second_cont;


RCS_lbl_rmv = {'RIFG', 'RSFG','RSGC', 'LSGC','LCaud','+'};
TW_lbl_add  = {'RMFG', 'RMFG', 'RACC', 'LACC','LCN',''};
hemi_lbl_mat = split(...
                    replace(...   
                        replace(...
                                peak_sum_tbl.labels_2, {' ', '-'}, '_'), ...
                                RCS_lbl_rmv, TW_lbl_add),...
                    '_');

% translate from 0:3, 8:11 (i.e., RC+S labels) to TW's 1:4 labels
hemi_lbl_mat(:, 3:4) = replace(hemi_lbl_mat(:, 3:4), ...
                               compose('%g', [8:11, 0:3]),...
                               compose('%g', [1:4, 1:4]));

first_cont = cellfun(@(x, y) sprintf('%s%s', x, y), ...
            hemi_lbl_mat(:,2), hemi_lbl_mat(:,3), ...
            'UniformOutput', false);

second_cont = cellfun(@(x, y) sprintf('%s%s', x, y), ...
            hemi_lbl_mat(:,2), hemi_lbl_mat(:,4), ...
            'UniformOutput', false);

peak_sum_tbl.labels_2_1_TW_format  = first_cont;
peak_sum_tbl.labels_2_2_TW_format  = second_cont;

end