function plot_hist(cfg, redcap, db_beh_RCSXX)

    figure('Units', 'Inches', 'Position', [0, 0, 15, 10])

    [~, redcap, date_range] = date_parser(cfg, redcap, db_beh_RCSXX );

    ds  =    datestr(date_range,'dd-mmm-yyyy');
    sgtitle([cfg.pt_id, newline, ds(1,:) ' to ' ds(2,:)], 'Fontsize',16);

    RCSXX_sum = calc_sum_stats(cfg, redcap, db_beh_RCSXX );

    
    subplot(3,2,[1,2])

        histogram(redcap.mayoNRS);    hold on;   histogram(redcap.worstNRS);

         ylabel('Numeric Rating Scale'); xlim([0,10])
             
         legend({...
             ['NRS Intensity (',...
               num2str(RCSXX_sum.mayoNRS(4)),...
               ' ',char(177),' ', ...
               num2str(RCSXX_sum.mayoNRS(5)),')']...
               ...
               ['NRS worst (', ...
               num2str(RCSXX_sum.worstNRS(4)),...
               ' ',char(177),' ', ...
               num2str(RCSXX_sum.worstNRS(5)),')']
              } ...
              );


         format_plot(); legend boxoff; 
            
    subplot(3,2,[3,4])

        histogram(redcap.painVAS, [0:3:48, 49:51, 52:3:100]);    
        hold on;   
        histogram(redcap.unpleasantVAS, [0:3:48, 49:51, 52:3:100]);

        ylabel('Visual Analog Scale');       xlim([0,100])

        legend({...
               ['VAS Intensity (',...
               num2str(RCSXX_sum.painVAS(4)),...
               ' ',char(177),' ', ...
               num2str(RCSXX_sum.painVAS(5)),')']...
               ...
               ['VAS Unpleasantness (', ...
               num2str(RCSXX_sum.unpleasantVAS(4)),...
               ' ',char(177),' ', ...
               num2str(RCSXX_sum.unpleasantVAS(5)),')'] ...
               } ...
               );

        prop_50_painVAS       = sum(redcap.painVAS == 50)./...
                                length(...
                                find(~isnan(redcap.painVAS)));

        prop_50_unpleasantVAS = sum(redcap.unpleasantVAS == 50)./...
                                length(...
                                find(~isnan(redcap.unpleasantVAS)));

        text(20, height(redcap)/6,...
            ['prob(50) Intensity VAS : ', num2str(prop_50_painVAS),...
            newline, 'prob(50) Unpleasant VAS: ', ...
            num2str(prop_50_unpleasantVAS)],...
            'FontSize', 14);
  
        format_plot(); legend boxoff; 

    subplot(3,2,[5, 6])


        MPQ_total     = redcap.MPQtotal;
        MPQ_aff       = sum([redcap.MPQsickening, redcap.MPQfearful, redcap.MPQcruel, redcap.MPQtiring],2,'omitnan');
        MPQ_som       = MPQ_total - MPQ_aff;


        histogram(MPQ_total, 'FaceAlpha', .75); hold on;
        histogram(MPQ_som,'FaceAlpha', .5);    hold on; 
        histogram(MPQ_aff);

        ylim([0, height(redcap)/3])

        
         legend({['MPQ Total (', ...
                    num2str(mean(MPQ_total)),...
                    ' ',char(177),' ', ...
                    num2str(std(MPQ_som)),...
                    ')'],...
                ['MPQ Somatic (',...
                    num2str(mean(MPQ_som)),...
                    ' ',char(177),' ', ...
                    num2str(std(MPQ_som)),...
                    ')'],...
                ['MPQ Affective (',...
                    num2str(mean(MPQ_aff)),...
                    ' ',char(177),' ', ...
                    num2str(std(MPQ_aff)),...
                    ')'],...
               });

         ylabel('McGill Pain Questionnaire')


         text(1, height(redcap)/4,...
             [num2str(sum(MPQ_aff == 0)),' MPQ aff reports were "0"'],...
             'Fontsize', 14)

        format_plot;  legend boxoff;    

    function format_plot()  

        set(gca,'fontSize',14, 'TickLength', [0 0]); 
        grid on;    grid MINOR;      box off
        
    end
end
