function plot_hist(cfg, REDcap)

    redcap  = REDcap.(cfg.pt_id);
    
    figure('Units', 'Inches', 'Position', [0, 0, 20, 15])

    [redcap, date_range] = date_parser(cfg, redcap);

    ds  =    datestr(date_range,'dd-mmm-yyyy');
    sgtitle([cfg.pt_id, newline, ds(1,:) ' to ' ds(2,:)], 'Fontsize',16);

    r_cap_sum = calc_sum_stats(cfg, redcap);

    
    subplot(3,2,[1,2])

    histogram(redcap.mayoNRS);  

    if any(strcmp(cfg.pt_id, {'RCS06', 'RCS07'})) || contains(cfg.pt_id, 's0')
        
        legend({...
                ['NRS Intensity (',...
                num2str(r_cap_sum.mayoNRS(4)),...
                ' ',char(177),' ', ...
                num2str(r_cap_sum.mayoNRS(5)),')']...
               } ...
              );

    else
        hold on

        histogram(redcap.worstNRS);
     
        legend({...
                ['NRS Intensity (',...
                num2str(r_cap_sum.mayoNRS(4)),...
                ' ',char(177),' ', ...
                num2str(r_cap_sum.mayoNRS(5)),')']...
                ...
                ['NRS worst (', ...
                num2str(r_cap_sum.worstNRS(4)),...
                ' ',char(177),' ', ...
                num2str(r_cap_sum.worstNRS(5)),')']
               } ...
              );
    end

    xlabel('Numeric Rating Scale');       xlim([0,10])

         
    format_plot(); legend boxoff; 
     
    % VAS histograms
    subplot(3,2,[3,4])

    histogram(redcap.painVAS, [0:3:48, 49:51, 52:3:100]);    
    hold on;   
    histogram(redcap.unpleasantVAS, [0:3:48, 49:51, 52:3:100]);
    

    legend({...
           ['VAS Intensity (',...
           num2str(r_cap_sum.painVAS(4)),...
           ' ',char(177),' ', ...
           num2str(r_cap_sum.painVAS(5)),')']...
           ...
           ['VAS Unpleasantness (', ...
           num2str(r_cap_sum.unpleasantVAS(4)),...
           ' ',char(177),' ', ...
           num2str(r_cap_sum.unpleasantVAS(5)),')'] ...
           } ...
           );


    prop_50_painVAS       = sum(redcap.painVAS == 50)./...
                            length(...
                            find(~isnan(redcap.painVAS)));

    prop_50_unpleasantVAS = sum(redcap.unpleasantVAS == 50)./...
                            length(...
                            find(~isnan(redcap.unpleasantVAS)));

    text(20, height(redcap)/10,...
        ['prob(50) Intensity VAS : ', num2str(prop_50_painVAS),...
        newline,...
        'prob(50) Unpleasantness VAS : ', num2str(prop_50_unpleasantVAS)],...
        'FontSize', 14);

    
    xlabel('Visual Analog Scale');       xlim([0,100])

    format_plot(); legend boxoff; 


    % MPQ histograms
    subplot(3,2,[5, 6])


        MPQ_total     = redcap.MPQtotal;
        MPQ_aff       = sum([redcap.MPQsickening, redcap.MPQfearful, redcap.MPQcruel, redcap.MPQtiring],2,'omitnan');
        MPQ_som       = MPQ_total - MPQ_aff;


        histogram(MPQ_total, 'FaceAlpha', .75); hold on;
        histogram(MPQ_som,'FaceAlpha', .5);    hold on; 
        histogram(MPQ_aff);

        ylim([0, height(redcap)/3])

        
         legend({['MPQ Total (', ...
                    num2str(mean(MPQ_total)),...
                    ' ',char(177),' ', ...
                    num2str(std(MPQ_total)),...
                    ')'],...
                ['MPQ Somatic (',...
                    num2str(mean(MPQ_som)),...
                    ' ',char(177),' ', ...
                    num2str(std(MPQ_som)),...
                    ')'],...
                ['MPQ Affective (',...
                    num2str(mean(MPQ_aff)),...
                    ' ',char(177),' ', ...
                    num2str(std(MPQ_aff)),...
                    ')'],...
               });

         xlabel('McGill Pain Questionnaire'); xlim([0,45])

         text(1, height(redcap)/4,...
             [num2str(sum(MPQ_aff == 0)), ...
             ' (' num2str(100*sum(MPQ_aff == 0)/height(MPQ_aff)), '%)'...
             ' of MPQ affective reports were "0"'],...
             'Fontsize', 14)

        format_plot;  legend boxoff;  
        
        if contains(cfg.pt_id, 'stage0')

            save_dir = [cd,'/plot_beh/figs/beh_only/', cfg.pt_id(end-4:end), '/stage_0/'];
        else

            save_dir = [cd,'/plot_beh/figs/beh_only/', cfg.pt_id];
        end

        if ~exist(save_dir, 'dir')  
         
            mkdir(save_dir)
        end

        saveas(gcf, [save_dir, '/beh_hist.png']);


    %% for RCS06, make seperate histograms for Noc and NP pain
    if strcmp(cfg.pt_id, 'RCS06')

        figure('Units', 'Inches', 'Position', [0, 0, 15, 10])
        sgtitle([cfg.pt_id, newline, ds(1,:) ' to ' ds(2,:)], 'Fontsize',16);


        % NRS Noc and NP
        subplot(211)
        histogram(redcap.nocNRS);  hold on; histogram(redcap.npNRS);  

        xlabel('Numeric Rating Scale'); xlim([0,10])


        legend( ...
              {...
                ['NRS Noc (',...
                num2str(r_cap_sum.nocNRS(4)),...
                ' ',char(177),' ', ...
                num2str(r_cap_sum.nocNRS(5)),')']...
                ...
                ['NRS NP (', ...
                num2str(r_cap_sum.npNRS(4)),...
                ' ',char(177),' ', ...
                num2str(r_cap_sum.npNRS(5)),')']
               } ...
              );

        format_plot(); legend boxoff; 


        % VAS NP and noc
        subplot(212)

        histogram(redcap.nocVAS, [0:3:48, 49:51, 52:3:100]); 
        hold on;  
        histogram(redcap.npVAS, [0:3:48, 49:51, 52:3:100]);
        
        legend( ...
              {['VAS Noc Inten. (', ...
                    num2str(r_cap_sum.nocVAS(4)),...
                    ' ',char(177),' ', ...
                    num2str(r_cap_sum.nocVAS(5)),')'] ...
                                        ...
                    ['VAS NP Intens.  (', ...
                    num2str(r_cap_sum.npVAS(4)),...
                    ' ',char(177),' ', ...
                    num2str(r_cap_sum.npVAS(5)),')']} ...
              );


        prop_50_VAS_noc     = sum(redcap.nocVAS == 50)./...
                                length(...
                                find(~isnan(redcap.nocVAS)));

        prop_50_VAS_np       = sum(redcap.npVAS == 50)./...
                                length(...
                                find(~isnan(redcap.npVAS)));

        text(20, height(redcap)/6,...
            ['prob(50) VAS Noc : ', num2str(prop_50_VAS_noc),...
            newline,...
            'prob(50) VAS NP : ', num2str(prop_50_VAS_np)],...
            'FontSize', 14);
    
        xlabel('Visual Analog Scale'); xlim([0,100])

        format_plot(); legend boxoff; 

        saveas(gcf, [cd, '/plot_beh/figs/beh_only/', cfg.pt_id, '/beh_hist_noc_np.png']);

    end

    function format_plot()  

        ylabel('N occurences')
        set(gca,'fontSize',14, 'TickLength', [0 0]); 
        grid on;    grid MINOR;      box off
        
    end
end
